Repository Jitensid/TabPort, pull requests merged in 2022-10, with the labels that each got.

#12 Added copy to clipboard button
  src/components/DownloadTabsList/DownloadTabsList.js
  src/utils/JSONFileOperations/JSONFileOperations.js
Labels: enhancement, hacktoberfest

#10 Text file support for TabPort Extension
  src/__tests__/Utils/FileFormat.test.js
  src/components/DownloadTabsList/DownloadTabsList.js
  src/utils/FileFormat.js
  src/utils/JSONFileOperations/JSONFileOperations.js
Labels: enhancement, hacktoberfest

#21 Fix Copy Button and FileFormat tests
  src/__tests__/Utils/FileFormat.test.js
  src/__tests__/Utils/JSONFileOperations.test.js
  src/__tests__/components/DownloadTabsList/DownloadTabsList.test.js
  src/utils/FileFormat.js
Labels: enhancement, good first issue, hacktoberfest, Test, Tests

#22 add excel file support
  package-lock.json
  package.json
  public/index.html
  src/__tests__/components/UploadButton/UploadButton.test.js
  src/components/DownloadTabsList/DownloadTabsList.js
  src/components/UploadButton/UploadButton.js
  src/utils/FileFormat.js
  src/utils/JSONFileOperations/JSONFileOperations.js
Labels: enhancement, hacktoberfest, New Feature
